### ISSUE TITLE
include

### ISSUE THREAD

**Issue by Voltron2** [alexeygritsenko/ASM-Visual-support#2]
не видит include от fasm =((
"
format PE GUI 4.0
entry start

include 'win32w.inc'
"
"prog1.asm [7]:
include 'win32w.inc'
error: file not found.
"
Д. include все на месте...

**Comment by alexeygritsenko** [comment]
Вам нужно определить где находятся эти файлы, путь должен быть относительно компилятора (fasm.exe). Если они находятся в доп. подкаталогах то их нужно указывать в пути, например include 'includes\win32w.inc'. Кроме того если вы добавили их в ссылки обозревателя проектов, то просто перетащите их в код.
