### ISSUE TITLE
Program crashes on closing clues

### ISSUE THREAD

**Issue by RDaneliya** [alexeygritsenko/ASM-Visual-support#5]
During typing if you try to close clues window with registers and command program crashes. It happens not always but very often
Here is my system configuration
[sysInfo.txt](https://github.com/alexeygritsenko/ASM-Visual-support/files/4638765/sysInfo.txt)

**Comment by alexeygritsenko** [comment]
Thanks, I think I already fixed it. will be available in the next update

**Comment by alexeygritsenko** [comment]
check in the new version https://gri-software.com/en/asmvisual/download
